# Basic build and deploy steps
[build]
  Command = "yarn build"
  Publish = "dist"

# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  